apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: howk

resources:
  - 00-echo-server.yaml
  - 01-stress-test.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: howk-stress-test
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

images:
  - name: howk-stress-test
    newTag: latest
